install.packages("shiny")
install.packages("tidyverse")
install.packages("magrittr")
install.packages("plotly")
install.packages("shinythemes")

install.packages("rtweet")
install.packages("lubridate")
install.packages("NLP")
install.packages("tidytext")
install.packages("wordcloud")
install.packages("reshape2")
install.packages("tm")
install.packages("tidyr")
install.packages("igraph")
install.packages("ggraph")
